// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_chothue_laptop.Models;

#nullable disable

namespace web_chothue_laptop.Migrations
{
    [DbContext(typeof(Swp391LaptopContext))]
    partial class Swp391LaptopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_chothue_laptop.Models.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("END_TIME");

                    b.Property<string>("IdNoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ID_NO_URL");

                    b.Property<long>("LaptopId")
                        .HasColumnType("bigint")
                        .HasColumnName("LAPTOP_ID");

                    b.Property<long?>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("STAFF_ID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("START_TIME");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("STATUS_ID");

                    b.Property<string>("StudentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STUDENT_URL");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TOTAL_PRICE");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK__BOOKING__3214EC275D19D412");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaptopId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StatusId");

                    b.ToTable("BOOKING", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.BookingReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOOKING_ID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("END_TIME");

                    b.Property<decimal?>("LateFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("LATE_FEE");

                    b.Property<int?>("LateMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("LATE_MINUTES");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("STAFF_ID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("START_TIME");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TOTAL_PRICE");

                    b.HasKey("Id")
                        .HasName("PK__BOOKING___3214EC2712A0AB23");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("BOOKING_RECEIPT", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BRAND_NAME");

                    b.HasKey("Id")
                        .HasName("PK__BRAND__3214EC27C3AE4F7C");

                    b.HasIndex(new[] { "BrandName" }, "UQ__BRAND__FBF4813685EAEB89")
                        .IsUnique();

                    b.ToTable("BRAND", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("BlackList")
                        .HasColumnType("bit")
                        .HasColumnName("BLACK_LIST");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("IdNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ID_NO");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.HasKey("Id")
                        .HasName("PK__CUSTOMER__3214EC27DA0E6190");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "Email" }, "UQ__CUSTOMER__161CF72465772F8F")
                        .IsUnique();

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Laptop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("BRAND_ID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("END_TIME");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMAGE_URL");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("MANAGER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("STATUS_ID");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("STUDENT_ID");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK__LAPTOP__3214EC27AA362BA4");

                    b.HasIndex("BrandId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StudentId");

                    b.ToTable("LAPTOP", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.LaptopDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CPU");

                    b.Property<string>("Gpu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GPU");

                    b.Property<long>("LaptopId")
                        .HasColumnType("bigint")
                        .HasColumnName("LAPTOP_ID");

                    b.Property<string>("Os")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("OS");

                    b.Property<string>("RamSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RAM_SIZE");

                    b.Property<string>("RamType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RAM_TYPE");

                    b.Property<string>("ScreenSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SCREEN_SIZE");

                    b.Property<string>("Storage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("STORAGE");

                    b.HasKey("Id")
                        .HasName("PK__LAPTOP_D__3214EC27977D8B22");

                    b.HasIndex("LaptopId");

                    b.ToTable("LAPTOP_DETAIL", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Manager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("IdNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ID_NO");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LAST_NAME");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("MANAGER_ID");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.HasKey("Id")
                        .HasName("PK__MANAGER__3214EC27B2D74430");

                    b.HasIndex("ManagerId");

                    b.HasIndex(new[] { "Email" }, "UQ__MANAGER__161CF724952E4047")
                        .IsUnique();

                    b.ToTable("MANAGER", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("Id")
                        .HasName("PK__ROLE__3214EC27367E6C9F");

                    b.HasIndex(new[] { "RoleName" }, "UQ__ROLE__2B9B877EDFE61C0F")
                        .IsUnique();

                    b.ToTable("ROLE", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Staff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("IdNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ID_NO");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<long?>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("STAFF_ID");

                    b.HasKey("Id")
                        .HasName("PK__STAFF__3214EC274C563AA1");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "Email" }, "UQ__STAFF__161CF7246254ACB9")
                        .IsUnique();

                    b.ToTable("STAFF", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("STATUS_NAME");

                    b.HasKey("Id")
                        .HasName("PK__STATUS__3214EC279CA1D331");

                    b.HasIndex(new[] { "StatusName" }, "UQ__STATUS__064B2D2D22983721")
                        .IsUnique();

                    b.ToTable("STATUS", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("IdNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ID_NO");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("Id")
                        .HasName("PK__STUDENT__3214EC27658F3E18");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "Email" }, "UQ__STUDENT__161CF724B0DFA8D3")
                        .IsUnique();

                    b.ToTable("STUDENT", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.StudentRentNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOOKING_ID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("MANAGER_ID");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MESSAGE");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("STUDENT_ID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id")
                        .HasName("PK__STUDENT___3214EC27AA9F8216");

                    b.HasIndex("BookingId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StudentId");

                    b.ToTable("STUDENT_RENT_NOTIFICATION", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Technical", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("IdNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ID_NO");

                    b.Property<long?>("IsWorking")
                        .HasColumnType("bigint")
                        .HasColumnName("IS_WORKING");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<long?>("TechnicalId")
                        .HasColumnType("bigint")
                        .HasColumnName("TECHNICAL_ID");

                    b.HasKey("Id")
                        .HasName("PK__TECHNICA__3214EC27F9334865");

                    b.HasIndex("IsWorking");

                    b.HasIndex("TechnicalId");

                    b.HasIndex(new[] { "Email" }, "UQ__TECHNICA__161CF724B6923E1A")
                        .IsUnique();

                    b.ToTable("TECHNICAL", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.TechnicalTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOOKING_ID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long>("LaptopId")
                        .HasColumnType("bigint")
                        .HasColumnName("LAPTOP_ID");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("STAFF_ID");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("STATUS_ID");

                    b.Property<long?>("TechnicalId")
                        .HasColumnType("bigint")
                        .HasColumnName("TECHNICAL_ID");

                    b.Property<string>("TechnicalResponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TECHNICAL_RESPONSE");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK__TECHNICA__3214EC27887CB471");

                    b.HasIndex("BookingId");

                    b.HasIndex("LaptopId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TechnicalId");

                    b.ToTable("TECHNICAL_TICKET", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.TicketList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("CustomerResponse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CUSTOMER_RESPONSE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ErrorImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ERROR_IMAGE_URL");

                    b.Property<decimal>("FixedCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("FIXED_COST");

                    b.Property<long>("LaptopId")
                        .HasColumnType("bigint")
                        .HasColumnName("LAPTOP_ID");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("STAFF_ID");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("STATUS_ID");

                    b.Property<long>("TechnicalTicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("TECHNICAL_TICKET_ID");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK__TICKET_L__3214EC275F5E9A5A");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaptopId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TechnicalTicketId");

                    b.ToTable("TICKET_LIST", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AVATAR_URL");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("OTP_CODE");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("OTP_EXPIRY");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("ROLE_ID");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("STATUS_ID");

                    b.HasKey("Id")
                        .HasName("PK__USER__3214EC2709715138");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "Email" }, "UQ__USER__161CF724C30A992C")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Booking", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_BOOKING_CUSTOMER");

                    b.HasOne("web_chothue_laptop.Models.Laptop", "Laptop")
                        .WithMany("Bookings")
                        .HasForeignKey("LaptopId")
                        .IsRequired()
                        .HasConstraintName("FK_BOOKING_LAPTOP");

                    b.HasOne("web_chothue_laptop.Models.Staff", "Staff")
                        .WithMany("Bookings")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_BOOKING_STAFF");

                    b.HasOne("web_chothue_laptop.Models.Status", "Status")
                        .WithMany("Bookings")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_BOOKING_STATUS");

                    b.Navigation("Customer");

                    b.Navigation("Laptop");

                    b.Navigation("Staff");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.BookingReceipt", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Booking", "Booking")
                        .WithMany("BookingReceipts")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_RECEIPT_BOOKING");

                    b.HasOne("web_chothue_laptop.Models.Customer", "Customer")
                        .WithMany("BookingReceipts")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_RECEIPT_CUSTOMER");

                    b.HasOne("web_chothue_laptop.Models.Staff", "Staff")
                        .WithMany("BookingReceipts")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_RECEIPT_STAFF");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Customer", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.User", "CustomerNavigation")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_CUSTOMER_USER");

                    b.Navigation("CustomerNavigation");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Laptop", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Brand", "Brand")
                        .WithMany("Laptops")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_LAPTOP_BRAND");

                    b.HasOne("web_chothue_laptop.Models.Manager", "Manager")
                        .WithMany("Laptops")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK_LAPTOP_MANAGER");

                    b.HasOne("web_chothue_laptop.Models.Status", "Status")
                        .WithMany("Laptops")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_LAPTOP_STATUS");

                    b.HasOne("web_chothue_laptop.Models.Student", "Student")
                        .WithMany("Laptops")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_LAPTOP_STUDENT");

                    b.Navigation("Brand");

                    b.Navigation("Manager");

                    b.Navigation("Status");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.LaptopDetail", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Laptop", "Laptop")
                        .WithMany("LaptopDetails")
                        .HasForeignKey("LaptopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LAPTOP_DETAIL_LAPTOP");

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Manager", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.User", "ManagerNavigation")
                        .WithMany("Managers")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK_MANAGER_USER");

                    b.Navigation("ManagerNavigation");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Staff", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.User", "StaffNavigation")
                        .WithMany("Staff")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_STAFF_USER");

                    b.Navigation("StaffNavigation");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Student", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.User", "StudentNavigation")
                        .WithMany("Students")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_STUDENT_USER");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.StudentRentNotification", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Booking", "Booking")
                        .WithMany("StudentRentNotifications")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_STUDENT_NOTIFICATION_BOOKING");

                    b.HasOne("web_chothue_laptop.Models.Manager", "Manager")
                        .WithMany("StudentRentNotifications")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK_STUDENT_NOTIFICATION_MANAGER");

                    b.HasOne("web_chothue_laptop.Models.Student", "Student")
                        .WithMany("StudentRentNotifications")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_STUDENT_NOTIFICATION_STUDENT");

                    b.Navigation("Booking");

                    b.Navigation("Manager");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Technical", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Status", "IsWorkingNavigation")
                        .WithMany("Technicals")
                        .HasForeignKey("IsWorking")
                        .HasConstraintName("FK_TECHNICAL_STATUS");

                    b.HasOne("web_chothue_laptop.Models.User", "TechnicalNavigation")
                        .WithMany("Technicals")
                        .HasForeignKey("TechnicalId")
                        .HasConstraintName("FK_TECHINICAL_USER");

                    b.Navigation("IsWorkingNavigation");

                    b.Navigation("TechnicalNavigation");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.TechnicalTicket", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Booking", "Booking")
                        .WithMany("TechnicalTickets")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_TT_BOOKING");

                    b.HasOne("web_chothue_laptop.Models.Laptop", "Laptop")
                        .WithMany("TechnicalTickets")
                        .HasForeignKey("LaptopId")
                        .IsRequired()
                        .HasConstraintName("FK_TT_LAPTOP");

                    b.HasOne("web_chothue_laptop.Models.Staff", "Staff")
                        .WithMany("TechnicalTickets")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_TT_STAFF");

                    b.HasOne("web_chothue_laptop.Models.Status", "Status")
                        .WithMany("TechnicalTickets")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_TT_STATUS");

                    b.HasOne("web_chothue_laptop.Models.Technical", "Technical")
                        .WithMany("TechnicalTickets")
                        .HasForeignKey("TechnicalId")
                        .HasConstraintName("FK_TT_TECH");

                    b.Navigation("Booking");

                    b.Navigation("Laptop");

                    b.Navigation("Staff");

                    b.Navigation("Status");

                    b.Navigation("Technical");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.TicketList", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Customer", "Customer")
                        .WithMany("TicketLists")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_TL_CUSTOMER");

                    b.HasOne("web_chothue_laptop.Models.Laptop", "Laptop")
                        .WithMany("TicketLists")
                        .HasForeignKey("LaptopId")
                        .IsRequired()
                        .HasConstraintName("FK_TL_LAPTOP");

                    b.HasOne("web_chothue_laptop.Models.Staff", "Staff")
                        .WithMany("TicketLists")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_TL_STAFF");

                    b.HasOne("web_chothue_laptop.Models.Status", "Status")
                        .WithMany("TicketLists")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_TL_STATUS");

                    b.HasOne("web_chothue_laptop.Models.TechnicalTicket", "TechnicalTicket")
                        .WithMany("TicketLists")
                        .HasForeignKey("TechnicalTicketId")
                        .IsRequired()
                        .HasConstraintName("FK_TL_TECH_TKT");

                    b.Navigation("Customer");

                    b.Navigation("Laptop");

                    b.Navigation("Staff");

                    b.Navigation("Status");

                    b.Navigation("TechnicalTicket");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.User", b =>
                {
                    b.HasOne("web_chothue_laptop.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_USER_ROLE");

                    b.HasOne("web_chothue_laptop.Models.Status", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_USER_STATUS");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Booking", b =>
                {
                    b.Navigation("BookingReceipts");

                    b.Navigation("StudentRentNotifications");

                    b.Navigation("TechnicalTickets");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Brand", b =>
                {
                    b.Navigation("Laptops");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Customer", b =>
                {
                    b.Navigation("BookingReceipts");

                    b.Navigation("Bookings");

                    b.Navigation("TicketLists");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Laptop", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LaptopDetails");

                    b.Navigation("TechnicalTickets");

                    b.Navigation("TicketLists");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Manager", b =>
                {
                    b.Navigation("Laptops");

                    b.Navigation("StudentRentNotifications");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Staff", b =>
                {
                    b.Navigation("BookingReceipts");

                    b.Navigation("Bookings");

                    b.Navigation("TechnicalTickets");

                    b.Navigation("TicketLists");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Status", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Laptops");

                    b.Navigation("TechnicalTickets");

                    b.Navigation("Technicals");

                    b.Navigation("TicketLists");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Student", b =>
                {
                    b.Navigation("Laptops");

                    b.Navigation("StudentRentNotifications");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.Technical", b =>
                {
                    b.Navigation("TechnicalTickets");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.TechnicalTicket", b =>
                {
                    b.Navigation("TicketLists");
                });

            modelBuilder.Entity("web_chothue_laptop.Models.User", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Managers");

                    b.Navigation("Staff");

                    b.Navigation("Students");

                    b.Navigation("Technicals");
                });
#pragma warning restore 612, 618
        }
    }
}
